const fs = require('fs');
const path = require('path');
const sharp = require('sharp');
const heicConvert = require('heic-convert');

const galleryDir = path.join('Assets', 'Life at Ayurgreen');
const outputJsPath = 'gallery_data.js';

async function processGallery() {
    if (!fs.existsSync(galleryDir)) {
        console.error(`Error: Gallery directory not found at ${galleryDir}`);
        process.exit(1);
    }

    const files = fs.readdirSync(galleryDir);
    console.log(`Found ${files.length} files in ${galleryDir}`);

    const sourceExtensions = ['.jpg', '.jpeg', '.png', '.heic'];
    
    for (const file of files) {
        const ext = path.extname(file).toLowerCase();
        if (!sourceExtensions.includes(ext)) {
            continue;
        }

        const srcPath = path.join(galleryDir, file);
        // Replace extension with .webp
        const webpName = file.replace(/\.[^/.]+$/, "") + ".webp";
        const destPath = path.join(galleryDir, webpName);

        // Check if WebP already exists and is newer than source
        if (fs.existsSync(destPath)) {
            const srcStat = fs.statSync(srcPath);
            const destStat = fs.statSync(destPath);
            if (destStat.mtime > srcStat.mtime) {
                console.log(`- ${webpName} is up-to-date. Skipping.`);
                continue;
            }
        }

        console.log(`- Converting ${file} to WebP...`);
        try {
            if (ext === '.heic') {
                const inputBuffer = fs.readFileSync(srcPath);
                // Convert HEIC to JPEG buffer in-memory
                const jpegBuffer = await heicConvert({
                    buffer: inputBuffer,
                    format: 'JPEG',
                    quality: 1
                });
                // Pass JPEG buffer to sharp to output WebP
                await sharp(jpegBuffer)
                    .webp({ quality: 80 })
                    .toFile(destPath);
                console.log(`  Converted HEIC: ${file} -> ${webpName}`);
            } else {
                await sharp(srcPath)
                    .webp({ quality: 80 })
                    .toFile(destPath);
                console.log(`  Converted standard: ${file} -> ${webpName}`);
            }
        } catch (err) {
            console.error(`  Failed to convert ${file}:`, err.message);
        }
    }

    // Now gather all webp files to generate the JS file
    const finalFiles = fs.readdirSync(galleryDir);
    const webpFiles = finalFiles.filter(f => f.toLowerCase().endsWith('.webp'));
    console.log(`\nTotal WebP images in gallery: ${webpFiles.length}`);

    // Generate gallery_data.js
    const jsLines = [
        `// Auto-generated by process_life_gallery.cjs`,
        `// Do not edit this file manually.`,
        ``,
        `export const galleryImages = [`
    ];

    webpFiles.forEach((file, index) => {
        const trailingComma = index === webpFiles.length - 1 ? '' : ',';
        // Note the path must be relative to the location of gallery_data.js
        jsLines.push(`    new URL('./Assets/Life at Ayurgreen/${file.replace(/'/g, "\\'")}', import.meta.url).href${trailingComma}`);
    });

    jsLines.push(`];`);
    jsLines.push(``);

    fs.writeFileSync(outputJsPath, jsLines.join('\n'), 'utf-8');
    console.log(`Successfully generated ${outputJsPath} with ${webpFiles.length} image imports!`);
}

processGallery();
